name: cd

# Controls when the workflow will run
on:
  release:
    types:
      - published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1

      # Runs a single command using the runners shell
      - run: cat $CRENDTIALS > $FLUTTER_ROOT/.pub_cache/credentials.json
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed --dry-run .
      - run: flutter analyze --no-fatal-infos
      - run: flutter test
      - run: flutter pub publish --dry-run
      - run: flutter pub publish
