name: ci

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.*/**'
  pull_request:
    types:
      - ready_for_review
      - synchronize
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ github.ref }}-${{ hashFiles('pubspec.yaml') }}
      - uses: subosito/flutter-action@v1
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos
      - run: flutter test

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ github.ref }}-${{ hashFiles('pubspec.yaml') }}
      - uses: subosito/flutter-action@v1
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed --dry-run .
